name: publish from prerelease

on:
  release:
    types: [prereleased]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
jobs:
  getDistTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: salesforcecli/github-workflows/.github/actions/getPreReleaseTag@prerelease-cca
  npm:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    needs: [getDistTag]
    with:
      tag: ${{ needs.getDistTag.outputs.tag }}
      githubTag: ${{ github.event.release.tag_name || inputs.tag }}

    secrets: inherit
