# test
name: version, tag and github release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@9962c3267b32873dbc552a38a8397194361e1101
        with:
          git-user-name: ${{ secrets.GH_USERNAME }}
          git-user-email: ${{ secrets.GH_EMAIL }}
          github-token: ${{ secrets.GH_TOKEN }}
          # Setting 'release-count' to 0 will keep ALL releases in the change log file (no pruning)
          release-count: '0'
          output-file: 'CHANGELOG.md'
      - name: Create Github Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        with:
          name: ${{ steps.changelog.outputs.tag }}
          tag: ${{ steps.changelog.outputs.tag }}
          commit: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GH_TOKEN }}
          skipIfReleaseExists: true
